services:
  - type: web
    name: cozy-heaven-backend
    runtime: docker
    plan: free
    healthCheckPath: /
    envVars:
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: APP_SELF_PING_URL
        sync: false